source "http://rubygems.org"
gem "daemons"
gem "capistrano"
gem "railsless-deploy"
gem "eventmachine"
gem "mysql2"
gem "redis"
gem "rake"
gem "http_parser.rb"
gem "sinatra"
gem "addressable", ">=2.1.1"
gem "em-websocket"
gem "sinatra"
gem "net-ldap"
gem "uuid"
gem "erubis"

#Temporary
gem "shotgun"
